kind: Deployment
apiVersion: apps/v1
metadata:
    name: adago-backend
    namespace: adago
spec:
    replicas: 3
    selector:
        matchLabels:
            app: adago-backend
    template:
        metadata:
            labels:
                app: adago-backend
        spec:
            containers:
                - name: adago-backend
                  image: 'encalls/adago-backend:latest'
                  ports:
                      - containerPort: 3000
