version: '3.7'
services:
    db:
        image: mysql:latest
        restart: always
        environment:
            MYSQL_DATABASE: app_db
            MYSQL_USER: encall
            MYSQL_PASSWORD: 123456789
            MYSQL_ROOT_PASSWORD: 123456789
        ports:
            - '3306:3306'
        volumes:
            - db_data:/var/lib/mysql
        networks:
            - app-network
    phpmyadmin:
        image: phpmyadmin
        restart: always
        environment:
            PMA_HOST: db
            MYSQL_ROOT_PASSWORD: 123456789
        ports:
            - '8080:80'
        networks:
            - app-network
networks:
    app-network:
        driver: bridge
volumes:
    db_data:
