apiVersion: cert-manager.io/v1
kind: ClusterIssuer # I'm using ClusterIssuer here
metadata:
    name: letsencrypt-prod
spec:
    acme:
        server: https://acme-v02.api.letsencrypt.org/directory
        email: apichataimimpat@gmail.com
        privateKeySecretRef:
            name: letsencrypt-prod
        solvers:
            - http01:
                  ingress:
                      class: traefik
